### ISSUE TITLE
运行脚本时报错

### ISSUE THREAD

**Issue by udndhej** [Akimio521/AutoFilm#19]
File "main.py", line 11
SyntaxError: Non-ASCII character '\xe5' in file main.py on line 11, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
请问这个是什么情况

**Comment by zpljd258** [comment]
同样的问题：
如果使用python3 main.py 运行：
[2024-02-21 11:28:12,264][INFO]<module>:当前的APP版本是：v1.0.1
[2024-02-21 11:28:12,265][INFO]<module>:配置文件路径：./config/config.yaml
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    autofilm.main(args.config_path)
  File "/root/AutoFilm-1.0.1/autofilm.py", line 135, in main
    p_threads = get_config_value("setting", "p_threads", config=config_data, error_message="processing线程数读取错误")
TypeError: get_config_value() missing 1 required keyword-only argument: 'default_value'


如果使用python main.py 
  File "main.py", line 11
SyntaxError: Non-ASCII character '\xe5' in file main.py on line 11, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details


上面均为同样的config.yaml得到的结果

希望大佬答复一下如何解决～

**Comment by Akimio521** [comment]
你的python和python3可能指向的不是同一个python程序，建议检查一下环境变量，另外，提供一下设备系统和python版本

**Comment by zpljd258** [comment]
我在两个设备上尝试过：
在ASUSTor AS6702T。运行了3.10版本，报错：
[2024-02-21 11:28:12,264][INFO]:当前的APP版本是：v1.0.1
[2024-02-21 11:28:12,265][INFO]:配置文件路径：./config/config.yaml
Traceback (most recent call last):
File "main.py", line 22, in
autofilm.main(args.config_path)
File "/root/AutoFilm-1.0.1/autofilm.py", line 135, in main
p_threads = get_config_value("setting", "p_threads", config=config_data, error_message="processing线程数读取错误")
TypeError: get_config_value() missing 1 required keyword-only argument: 'default_value'


在vps上。ubuntu 20版，python 3.8，得到同样的报错。

感谢回复

**Comment by zpljd258** [comment]
我尝试git了您12小时之前更新的版本

这次可以运行了，但是遇到了网络错误

python3 main.py 
[2024-02-22 00:37:19,321][INFO]<module>:当前的APP版本是：v1.0.1
[2024-02-22 00:37:19,321][INFO]<module>:配置文件路径：config/config.yaml
[2024-02-22 00:37:19,326][INFO]__init__:输出目录：./media/；list_files线程数：3；processing_file线程数：8
[2024-02-22 00:37:19,327][INFO]run:开始生成[TV]Webdav服务器的Strm文件；剩余3个Webdav服务器未进行
[2024-02-22 00:37:19,327][WARNING]get_config_value:Alist令牌token读取错误，默认关闭，错误信息：'token'
[2024-02-22 00:37:24,331][WARNING]list_files:list_files线程1遇到错误，第1尝试失败；错误信息：Request to http://192.168.50.236:5244/dav/阿里云盘/TV-Shows/ failed with code 502 and message: b''，传入URL：http://192.168.50.236:5244/dav/阿里云盘/TV-Shows



重复一直提示这样的错误并且尝试过使用域名/更换为localhost/127.0.0.1均会报告上述错误。改路径确认在其他客户端可读

该文件夹下面还包含了
TV-Shows-Arrow-Arrow.S07E08.Unmasked.1080p.AMZN.WEB-DL.DDP5.1.H.264-CasStudio-thumb.jpg
这样的路径。希望能够帮忙看看如何解决

 非常感谢

**Comment by Akimio521** [comment]
> 您好，我通过git拉取了最新的文件后可以正常运行了。 但是有一个问题。 我在云盘上已经整理好了文件，但是生成strm文件的时候会将所有的视频文件混在一起变得比较杂乱。
> 
> 我想知道这是否是yaml配置的问题？我希望能够根据云盘上的文件目录格式生成对应目录格式下的strm文件
> 
> 非常感谢您的项目，它非常有用！

这个是我准备配置的一个新功能，可以用其他软件本地刮削配置更详细的媒体库路径，但当前版本还未增加开关，你重新pull一下应该就能恢复正常

**Comment by zpljd258** [comment]
> > 您好，我通过git拉取了最新的文件后可以正常运行了。 但是有一个问题。 我在云盘上已经整理好了文件，但是生成strm文件的时候会将所有的视频文件混在一起变得比较杂乱。
> > 我想知道这是否是yaml配置的问题？我希望能够根据云盘上的文件目录格式生成对应目录格式下的strm文件
> > 非常感谢您的项目，它非常有用！
> 
> 这个是我准备配置的一个新功能，可以用其他软件本地刮削配置更详细的媒体库路径，但当前版本还未增加开关，你重新pull一下应该就能恢复正常

有个虽然和项目不是很相关的额外问题请教：

尝试播放的时候会报错，发现jellyfin会将视频走通过服务器中转

已经尝试关闭了所有转码功能目前还是一样的问题，您建议做如何的设置以便于让Jellyfin进行直链播放吗？

客户端：iOS/infuse7.7/Jellyfin最新中国特供版

感谢！

**Comment by Akimio521** [comment]
最新版本已增加编码格式`# -*- coding:utf-8 -*-`，推荐使用python3.11及以上版本，若还有编码问题请重新打开Issue
