### ISSUE TITLE
cannot import name 'TaskGroup' from 'asyncio' 

### ISSUE THREAD

**Issue by liquidsnake9** [Akimio521/AutoFilm#36]
Traceback (most recent call last):
  File "/root/AutoFilm/main.py", line 5, in <module>
    import autofilm
  File "/root/AutoFilm/autofilm.py", line 6, in <module>
    from modules import Alist2Strm
  File "/root/AutoFilm/modules/__init__.py", line 1, in <module>
    from .Alist2Strm import Alist2Strm
  File "/root/AutoFilm/modules/Alist2Strm.py", line 11, in <module>
    from alist import AlistFileSystem, AlistPath
  File "/usr/local/lib/python3.10/dist-packages/alist/__init__.py", line 25, in <module>
    from asyncio import get_running_loop, run, TaskGroup
ImportError: cannot import name 'TaskGroup' from 'asyncio' (/usr/lib/python3.10/asyncio/__init__.py)

依赖包已安装，为啥还会出现这个错误？
python版本是3.10.7

**Comment by Akimio521** [comment]
看样子是python-alist的问题，可能是引入了新版本的特性吧，目前版本我只在3.11和3.12中测试过，有需要可以在[web-mount-packs](https://github.com/ChenyangGao/web-mount-packs)提交issue排查

**Comment by liquidsnake9** [comment]
找到问题了，python版本问题，3.10不行，TaskGroup这个模块是3.11新加入的，所有最低需要3.11
另外，链接到的教程网页已经过时了，yaml都是错的

**Comment by Akimio521** [comment]
是的，文档一直没时间改
