### ISSUE TITLE
docker akimio/autofilm:Dev-20240707运行报错，latest版登录失败 

### ISSUE THREAD

**Issue by hanlihanshaobo** [Akimio521/AutoFilm#43]
Dev-20240707 报错如下
正在执行主程序...
[2024-07-08 01:23:14,095][INFO]:当前的APP版本是：v1.1.2-2
[2024-07-08 01:23:14,095][INFO]:配置文件路径：/config/config.yaml
[2024-07-08 01:23:14,100][INFO]init:===================输出目录：/media====================
[2024-07-08 01:23:14,100][DEBUG]run_Alist2Strm:Alist服务器加载成功
[2024-07-08 01:23:14,101][DEBUG]load_ssl_context:load_ssl_context verify=True cert=None trust_env=True http2=False
[2024-07-08 01:23:14,102][DEBUG]load_ssl_context_verify:load_verify_locations cafile='/usr/local/lib/python3.12/site-packages/certifi/cacert.pem'
[2024-07-08 01:23:14,128][DEBUG]trace:connect_tcp.started host='192.168.2.174' port=5244 local_address=None timeout=5 socket_options=None
[2024-07-08 01:23:14,130][DEBUG]trace:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f6bb24cfd70>
[2024-07-08 01:23:14,131][DEBUG]trace:send_request_headers.started request=<Request [b'POST']>
[2024-07-08 01:23:14,131][DEBUG]trace:send_request_headers.complete
[2024-07-08 01:23:14,131][DEBUG]trace:send_request_body.started request=<Request [b'POST']>
[2024-07-08 01:23:14,131][DEBUG]trace:send_request_body.complete
[2024-07-08 01:23:14,131][DEBUG]trace:receive_response_headers.started request=<Request [b'POST']>
[2024-07-08 01:23:14,134][DEBUG]trace:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Date', b'Sun, 07 Jul 2024 17:23:14 GMT'), (b'Content-Length', b'255')])
[2024-07-08 01:23:14,135][INFO]_send_single_request:HTTP Request: POST http://192.168.2.174:5244/api/auth/login/hash "HTTP/1.1 200 OK"
[2024-07-08 01:23:14,135][DEBUG]trace:receive_response_body.started request=<Request [b'POST']>
[2024-07-08 01:23:14,135][DEBUG]trace:receive_response_body.complete
[2024-07-08 01:23:14,135][DEBUG]trace:response_closed.started
[2024-07-08 01:23:14,136][DEBUG]trace:response_closed.complete
Traceback (most recent call last):
File "/app/main.py", line 29, in
my_autofilm.run_Alist2Strm()
File "/app/autofilm.py", line 74, in run_Alist2Strm
alist2strm = Alist2Strm(
^^^^^^^^^^^
File "/app/modules/alist2strm.py", line 63, in init
self.base_dir = client.fs.abspath(base_dir)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alist/component/fs.py", line 2637, in abspath
path = fspath(path)
^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
等待 3600 秒后再次执行...

**Comment by Akimio521** [comment]
最近大幅度重构
建议docker pull akimio/autofilm:DEV
参考配置文件重新配置

**Comment by hanlihanshaobo** [comment]
> 最近大幅度重构 建议docker pull akimio/autofilm:DEV 参考配置文件重新配置

[INFO]2024-07-08 15:31:13,873 - AutoFilm启动中，当前的APP版本是：v1.1.2-2
最新的卡在这了

**Comment by Akimio521** [comment]
有可能是配置文件设置有误，如果无误会有`logger.info(f"{server["id"]}已被添加至后台任务")`或是`logger.warning(f"{server["id"]}未设置Cron")`的日志被打印

**Comment by Akimio521** [comment]
已经修复了错误提示，重新拉取镜像试试

**Comment by hanlihanshaobo** [comment]
> 已经修复了错误提示，重新拉取镜像试试

##### 配置文件能加载了，现在提示alist服务器检测不到，这是我的配置
AlistServerList:
  - id: 电视剧
    cron: 22 * * * *                  # 后台定时任务 Crontable 表达式
    url: http://192.168.1.14:5244     # Alist 服务器地址
    username: alist                   # Alist 账号
    password: 1234              # Alist 密码
    token:                            # AList 未启用签名时，设置为空字符串
    source_dir: /电视剧                 # Alist 服务器上文件夹路径
    target_dir: /media/电影             # 输出路径
    flatten_mode: False               # 平铺模式，开启后 subtitle、image、nfo 强制关闭(可选，默认 False)
    subtitle: False                   # 是否下载字幕文件(可选，默认 False)
    image: False                      # 是否下载图片文件(可选，默认 False)
    nfo: False                        # 是否下载 .nfo 文件(可选，默认 False)
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件(可选，默认 False)
    max_workers: 5                    # 下载文件最大并发数(可选，默认 5)

**Comment by hanlihanshaobo** [comment]
> 我的参考配置文件写错了，把`AlistServerList`改成`Alist2StrmList`，刚刚已经修正错误重新提交了

##### 运行起来了，感谢，今天效率好高
INFO]2024-07-08 21:08:59,589 - AutoFilm 启动中，当前的APP版本是：v1.2.0
[INFO]2024-07-08 21:08:59,624 - 检测到 Alist 服务器配置，正在添加至后台任务
[INFO]2024-07-08 21:08:59,693 - 电视剧已被添加至后台任务
[INFO]2024-07-08 21:08:59,722 - 电影已被添加至后台任务
[INFO]2024-07-08 21:11:44,677 - AutoFilm 启动中，当前的APP版本是：v1.2.0
[INFO]2024-07-08 21:11:44,684 - 检测到 Alist 服务器配置，正在添加至后台任务
[INFO]2024-07-08 21:11:44,765 - 电视剧已被添加至后台任务
[INFO]2024-07-08 21:11:44,794 - 电影已被添加至后台任务
[DEBUG]2024-07-08 21:12:00,261 - 创建文件：PosixPath('/media/电视剧/内容违规已屏蔽-1720411708/3.Body.Problem.S01E03.2024.2160p.NF.WEB-DL.DDP5.1.Atmos.DV.HDR.H.265.strm')
[DEBUG]202

**Comment by Akimio521** [comment]
是说我人呢还是说程序🤔没有其他问题可以关闭该issue了

**Comment by hanlihanshaobo** [comment]
> 是说我人呢还是说程序🤔没有其他问题可以关闭该issue了

今天更新效率高😀👍

**Comment by hanlihanshaobo** [comment]
##### 生成的strm文件访问后是这样的，正常是不是直接自动下载
{
    "code": 401,
    "message": "expire missing",
    "data": null
}

**Comment by Akimio521** [comment]
alist是开启了签名吗

**Comment by hanlihanshaobo** [comment]
> alist是开启了签名吗

没开启

**Comment by hanlihanshaobo** [comment]
> alist是开启了签名吗

alist默认开启签名的，关了后可以了，谢谢

**Comment by Akimio521** [comment]
开启签名可以填写配置文件的token，这样也可以使用，不过需要注意需要将过期时间设为永不过期
