### ISSUE TITLE
 每次清理完过期的strm就会报错

### ISSUE THREAD

**Issue by ttkjk** [Akimio521/AutoFilm#71]
配置文件如下:
Settings:
  DEV: False                          # 开发者模式(可选，默认 False)

Alist2StrmList:
    
  - id: 123First                          # 标识 ID
    cron: 0 */3 * * *                  # 后台定时任务 Cron 表达式
    url: http://192.168.0.109:5244     # Alist 服务器地址
    token: alist-86d4ebc8-2304-43fe-9df8-f0aa46fc1a9b9k10K22Qv14nOPVC1rifskk0WrWjTXZVTxEHTopvtBPmOKI6mdXPlTx29sIrswt4      
    source_dir: /123/资源库/媒体库                 # Alist 服务器上文件夹路径
    target_dir: /media/123             # 输出路径
    flatten_mode: False               # 平铺模式，开启后 subtitle、image、nfo 强制关闭(可选，默认 False)
    subtitle: True                   # 是否下载字幕文件（可选，默认 False）
    image: True                      # 是否下载图片文件（可选，默认 False）
    nfo: True                        # 是否下载 .nfo 文件（可选，默认 False）
    mode: AlistURL                    # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 2                # 最大同时下载文件数（可选，默认 5）
    
  - id: 123Second
    cron: 0 */3 * * *                  # 后台定时任务 Cron 表达式
    url: http://192.168.0.109:5244     # Alist 服务器地址
    token: alist-86d4ebc8-2304-43fe-9df8-f0aa46fc1a9b9k10K22Qv14nOPVC1rifskk0WrWjTXZVTxEHTopvtBPmOKI6mdXPlTx29sIrswt4      
    source_dir: /1232/资源库/媒体库
    target_dir: /media/1232 
    flatten_mode: False               # 平铺模式，开启后 subtitle、image、nfo 强制关闭(可选，默认 False)
    subtitle: True                   # 是否下载字幕文件（可选，默认 False）
    image: True                      # 是否下载图片文件（可选，默认 False）
    nfo: True                        # 是否下载 .nfo 文件（可选，默认 False）
    mode: AlistURL                    # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 2                # 最大同时下载文件数（可选，默认 5）

运行日志如下：
【INFO】     2024-12-02 20:58:34 | AutoFilm v1.2.5 启动中...
【INFO】     2024-12-02 20:58:34 | 检测到 Alist2Strm 模块配置，正在添加至后台任务
【INFO】     2024-12-02 20:58:34 | 123First 已被添加至后台任务
【INFO】     2024-12-02 20:58:34 | 123Second 已被添加至后台任务
【WARNING】  2024-12-02 20:58:34 | 未检测到 Ani2Alist 模块配置
【INFO】     2024-12-02 20:58:34 | AutoFilm 启动完成
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f1ea6f667b0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f1ea6407cb0>, 42508.185607175)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f1ea66a79b0>
【INFO】     2024-12-02 21:00:07 | 白夜追凶.2017.S02E22.2160p.HQ.10bit.WEB-DL.H265.AAC.strm 创建成功
【INFO】     2024-12-02 21:00:19 | 小静与爸爸.Shizuka-chan and Papa.2022.S01E05.HDTV.1080p.H.264.AAC.strm 创建成功
【INFO】     2024-12-02 21:00:19 | 小静与爸爸.Shizuka-chan and Papa.2022.S01E02.HDTV.1080p.H.264.AAC.strm 创建成功
【INFO】     2024-12-02 21:00:19 | 小静与爸爸.Shizuka-chan and Papa.2022.S01E07.HDTV.1080p.H.264.AAC.strm 创建成功
【INFO】     2024-12-02 21:00:19 | 小静与爸爸.Shizuka-chan and Papa.2022.S01E03.HDTV.1080p.H.264.AAC.strm 创建成功
【INFO】     2024-12-02 21:00:19 | 小静与爸爸.Shizuka-chan and Papa.2022.S01E06.HDTV.1080p.H.264.AAC.strm 创建成功
【INFO】     2024-12-02 21:00:19 | 小静与爸爸.Shizuka-chan and Papa.2022.S01E04.HDTV.1080p.H.264.AAC.strm 创建成功
【INFO】     2024-12-02 21:00:19 | 小静与爸爸.Shizuka-chan and Papa.2022.S01E01.HDTV.1080p.H.264.AAC.strm 创建成功
【INFO】     2024-12-02 21:00:19 | 小静与爸爸.Shizuka-chan and Papa.2022.S01E08.HDTV.1080p.H.264.AAC.strm 创建成功
【INFO】     2024-12-02 21:01:12 | 我们陷入恋爱的理由.The Reason We Fall In Love.2024.S01E08.WEB-DL.1080p.H.264.AAC.strm 创建成功
【INFO】     2024-12-02 21:01:18 | 狮子的藏身处.Light of My Lion.2024.S01E08.WEB-DL.1080p.H.264.AAC.strm 创建成功
【INFO】     2024-12-02 21:01:32 | 各自孤独的美食家.それぞれの孤独のグルメ.2024.S01E09.WEB-DL.1080p.H.264.AAC.strm 创建成功
【INFO】     2024-12-02 21:13:16 | Alist2Strm处理完成
【INFO】     2024-12-02 21:13:16 | 开始清理本地文件
【INFO】     2024-12-02 21:13:17 | 清理过期的 .strm 文件完成
Job "Alist2Strm.run (trigger: cron[month='*', day='*', day_of_week='*', hour='*/3', minute='0'], next run at: 2024-12-03 00:00:00 CST)" raised an exception
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.12/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
  |     retval = await job.func(*job.args, **job.kwargs)
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/app/modules/alist2strm/alist2strm.py", line 133, in run
  |     async with TaskGroup() as tg:
  |   File "/usr/local/lib/python3.12/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/app/modules/alist2strm/alist2strm.py", line 138, in run
    |     async for path in client.iter_path(
    |   File "/app/api/alist/v3/client.py", line 452, in iter_path
    |     async for child_path in self.iter_path(
    |   File "/app/api/alist/v3/client.py", line 452, in iter_path
    |     async for child_path in self.iter_path(
    |   File "/app/api/alist/v3/client.py", line 452, in iter_path
    |     async for child_path in self.iter_path(
    |   File "/app/api/alist/v3/client.py", line 450, in iter_path
    |     for path in await self.async_api_fs_list(dir_path):
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/utils/retry.py", line 89, in f_retry
    |     return await f(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/api/alist/v3/client.py", line 219, in async_api_fs_list
    |     async with self.__session.post(api_url, data=payload) as resp:
    |   File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1353, in __aenter__
    |     self._resp = await self._coro
    |                  ^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 684, in _request
    |     await resp.start(conn)
    |   File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 999, in start
    |     message, payload = await protocol.read()  # type: ignore[union-attr]
    |                        ^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    |     await self._waiter
    | aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
    +------------------------------------

每次清理完过期的strm就会报错。

**Comment by Akimio521** [comment]
已修复，docker版本未更新

**Comment by ttkjk** [comment]
Job "Alist2Strm.run (trigger: cron[month='*', day='*', day_of_week='*', hour='23', minute='11'], next run at: 2024-12-04 23:11:00 CST)" raised an exception
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.12/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
  |     retval = await job.func(*job.args, **job.kwargs)
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/app/modules/alist2strm/alist2strm.py", line 130, in run
  |     async with TaskGroup() as tg:
  |   File "/usr/local/lib/python3.12/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/app/modules/alist2strm/alist2strm.py", line 134, in run
    |     async for path in client.iter_path(
    |   File "/app/modules/alist/v3/client.py", line 375, in iter_path
    |     for path in await self.async_api_fs_list(dir_path):
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/modules/alist/v3/client.py", line 219, in async_api_fs_list
    |     AlistPath(
    |   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    |     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | pydantic_core._pydantic_core.ValidationError: 1 validation error for AlistPath
    | hash_info
    |   Input should be a valid string [type=string_type, input_value={'sha1': ''}, input_type=dict]
    |     For further information visit https://errors.pydantic.dev/2.9/v/string_type
    +------------------------------------
更换dev标签以后，115生成strm会报错，好像处理alistpath的时候有问题

**Comment by Akimio521** [comment]
重新拉取镜像再试试

**Comment by ttkjk** [comment]
strm能够正常生成了，但是出现了下载元数据(nfo、图片、字幕)的时候会报错。日志如下：

【WARNING】  2024-12-04 21:12:28 | /media/115First/movies/外语电影/小丑2： 双重妄想 (2024) {tmdb-889737}/小丑2： 双重妄想(2024) - 2160p.H.265.WEB-DL HDR10.chs.srt 处理失败，详细信息：unsupported operand type(s) for ** or pow(): 'dict' and 'dict'，3秒后重试 ...
【WARNING】  2024-12-04 21:12:28 | /media/115First/movies/外语电影/小丑2： 双重妄想 (2024) {tmdb-889737}/小丑2： 双重妄想(2024) - 2160p.H.265.WEB-DL HDR10.cht.srt 处理失败，详细信息：unsupported operand type(s) for ** or pow(): 'dict' and 'dict'，3秒后重试 ...
【INFO】     2024-12-04 21:12:30 | 死侍与金刚狼(2024) - 2160p.H.265.Ultra HD Blu-ray Remux HDR10.strm 创建成功
【INFO】     2024-12-04 21:12:30 | 死侍与金刚狼(2024) - 2160p.H.265.WEB-DL AMZN.strm 创建成功
【INFO】     2024-12-04 21:12:31 | 东京死劫：布莱克曼命案(2023).strm 创建成功
【WARNING】  2024-12-04 21:12:31 | /media/115First/movies/外语电影/小丑2： 双重妄想 (2024) {tmdb-889737}/小丑2： 双重妄想(2024) - 2160p.H.265.WEB-DL HDR10.chs.srt 处理失败，详细信息：unsupported operand type(s) for ** or pow(): 'dict' and 'dict'，6秒后重试 ...
【WARNING】  2024-12-04 21:12:31 | /media/115First/movies/外语电影/小丑2： 双重妄想 (2024) {tmdb-889737}/小丑2： 双重妄想(2024) - 2160p.H.265.WEB-DL HDR10.cht.srt 处理失败，详细信息：unsupported operand type(s) for ** or pow(): 'dict' and 'dict'，6秒后重试 ...
【INFO】     2024-12-04 21:12:33 | 心理罪(2017) - 2160p.H.265 10-bit.WEB-DL.strm 创建成功
【INFO】     2024-12-04 21:12:34 | 钢的琴(2011) - 2160p.H.265.WEB-DL.strm 创建成功
【INFO】     2024-12-04 21:12:35 | 街娃儿(2021) - 1080p.H.264.Blu-ray.strm 创建成功
【INFO】     2024-12-04 21:12:36 | 绑架游戏(2024) - 2160p.H265.WEB-DL.strm 创建成功
【INFO】     2024-12-04 21:12:37 | 年少日记(2023) - 1080p.H.264.Blu-ray Remux.strm 创建成功
【ERROR】    2024-12-04 21:12:37 | /media/115First/movies/外语电影/小丑2： 双重妄想 (2024) {tmdb-889737}/小丑2： 双重妄想(2024) - 2160p.H.265.WEB-DL HDR10.chs.srt 处理失败，详细信息：unsupported operand type(s) for ** or pow(): 'dict' and 'dict'，超出最大重试次数！
【ERROR】    2024-12-04 21:12:37 | /media/115First/movies/外语电影/小丑2： 双重妄想 (2024) {tmdb-889737}/小丑2： 双重妄想(2024) - 2160p.H.265.WEB-DL HDR10.cht.srt 处理失败，详细信息：unsupported operand type(s) for ** or pow(): 'dict' and 'dict'，超出最大重试次数！
【WARNING】  2024-12-04 21:12:54 | /media/115First/movies/华语电影/周处除三害 (2023) {tmdb-1046090}/fanart.jpg 处理失败，详细信息：unsupported operand type(s) for ** or pow(): 'dict' and 'dict'，3秒后重试 ...
【WARNING】  2024-12-04 21:12:54 | /media/115First/movies/华语电影/周处除三害 (2023) {tmdb-1046090}/logo.png 处理失败，详细信息：unsupported operand type(s) for ** or pow(): 'dict' and 'dict'，3秒后重试 ...
【WARNING】  2024-12-04 21:12:54 | /media/115First/movies/华语电影/周处除三害 (2023) {tmdb-1046090}/poster.jpg 处理失败，详细信息：unsupported operand type(s) for ** or pow(): 'dict' and 'dict'，3秒后重试 ...
【WARNING】  2024-12-04 21:12:54 | /media/115First/movies/华语电影/周处除三害 (2023) {tmdb-1046090}/周处除三害.The Pig the Snake and the Pigeon.2023.{edition-WEB-DL}.1080p.H264.DDP 5.1.nfo 处理失败，详细信息：unsupported operand type(s) for ** or pow(): 'dict' and 'dict'，3秒后重试 ...

**Comment by Akimio521** [comment]
再更新看看

**Comment by ttkjk** [comment]
Job "Alist2Strm.run (trigger: cron[month='*', day='*', day_of_week='*', hour='0', minute='22'], next run at: 2024-12-06 00:22:00 CST)" raised an exception
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.12/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
  |     retval = await job.func(*job.args, **job.kwargs)
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/app/modules/alist2strm/alist2strm.py", line 130, in run
  |     async with TaskGroup() as tg:
  |   File "/usr/local/lib/python3.12/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/app/modules/alist2strm/alist2strm.py", line 131, in run
    |     client = AlistClient(
    |              ^^^^^^^^^^^^
    |   File "/app/utils/multiton.py", line 14, in __call__
    |     cls._instances[key] = super().__call__(*args, **kwargs)
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/modules/alist/v3/client.py", line 54, in __init__
    |     self.sync_api_me()
    |   File "/app/modules/alist/v3/client.py", line 167, in sync_api_me
    |     resp = self.__client.get(self.url + "/api/me", headers=headers, sync=True)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/utils/http.py", line 175, in get
    |     return self.request("get", url, sync=sync, params=params, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/utils/http.py", line 119, in request
    |     return self._sync_request(method, url, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | TypeError: update_wrapper() got multiple values for argument 'wrapped'
    +------------------------------------
有新的报错
